language: r
sudo: false
cache: packages

before_install:
  - tlmgr install bera nowidow parnotes marginfix

r:
  - devel
bioc_required: true
bioc_use_devel: true

warnings_are_errors: false

r: bioc-devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
